// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpportunityOs.Api.Data;

#nullable disable

namespace OpportunityOs.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("OpportunityOs.Api.Domain.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId")
                        .IsUnique();

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Clicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Downloads")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Installs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlatformFriction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionOrWaitlist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RevenueCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Sales")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Users")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.ToTable("Evidence", t =>
                        {
                            t.HasCheckConstraint("CK_Evidence_Clicks", "Clicks IS NULL OR Clicks >= 0");

                            t.HasCheckConstraint("CK_Evidence_Downloads", "Downloads IS NULL OR Downloads >= 0");

                            t.HasCheckConstraint("CK_Evidence_Installs", "Installs IS NULL OR Installs >= 0");

                            t.HasCheckConstraint("CK_Evidence_RevenueCents", "RevenueCents >= 0");

                            t.HasCheckConstraint("CK_Evidence_Sales", "Sales IS NULL OR Sales >= 0");

                            t.HasCheckConstraint("CK_Evidence_Users", "Users IS NULL OR Users >= 0");

                            t.HasCheckConstraint("CK_Evidence_Views", "Views IS NULL OR Views >= 0");
                        });
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Experiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BudgetCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StopCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeBudgetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.ToTable("Experiments", t =>
                        {
                            t.HasCheckConstraint("CK_Experiment_BudgetCents", "BudgetCents = 0");

                            t.HasCheckConstraint("CK_Experiment_TimeBudgetMinutes", "TimeBudgetMinutes >= 0");
                        });
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Constraints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessCriteria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiRestrictions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Friction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Geography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoneyMechanism")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayoutRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProbabilityToFirstDollar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReusableValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhyNow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("Opportunities", t =>
                        {
                            t.HasCheckConstraint("CK_Opportunity_ProbabilityToFirstDollar", "ProbabilityToFirstDollar >= 0 AND ProbabilityToFirstDollar <= 100");
                        });
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Decision", b =>
                {
                    b.HasOne("OpportunityOs.Api.Domain.Experiment", "Experiment")
                        .WithOne("Decision")
                        .HasForeignKey("OpportunityOs.Api.Domain.Decision", "ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Evidence", b =>
                {
                    b.HasOne("OpportunityOs.Api.Domain.Experiment", "Experiment")
                        .WithMany("Evidence")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Experiment", b =>
                {
                    b.HasOne("OpportunityOs.Api.Domain.Opportunity", "Opportunity")
                        .WithMany("Experiments")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Opportunity", b =>
                {
                    b.HasOne("OpportunityOs.Api.Domain.Goal", "Goal")
                        .WithMany("Opportunities")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Experiment", b =>
                {
                    b.Navigation("Decision");

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Goal", b =>
                {
                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("OpportunityOs.Api.Domain.Opportunity", b =>
                {
                    b.Navigation("Experiments");
                });
#pragma warning restore 612, 618
        }
    }
}
